spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: wasiflatifhussain
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: fitness-oauth2
    client-id: fitness-user-service-client
    client-secret: ${CLIENT_SECRET}
    grant-type: client_credentials


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/